import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import "./components/fontawsome";
import { Footer } from "./components/footer/Index";
import { Navbar } from "./components/navbar/Navbar";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta-sans',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.variable}>
          <header>
            <Navbar />
          </header>
          <main className="xl:mx-40 mx-9">
            {children}
          </main>
          <footer className="bg-gray-light">
            <Footer />
          </footer>
      </body>
    </html>
  );
}
